# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Rabt
tagline:          In passing
description:      
url:              http://raheelahmad.github.io
baseurl:          /

author:
  name:           'Raheel Ahmad'
  url:            https://twitter.com/raheel

paginate:         5

# Custom vars
version:          2.1.0
